2025-03-18 16:02:22,889 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-19 10:41:37,023 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 15:57:58,790 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:23:45,519 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:23:46,066 - root - ERROR - Lỗi khi tải dữ liệu giao dịch: name 'order_type' is not defined
2025-03-20 16:23:56,242 - root - ERROR - Lỗi khi tải dữ liệu giao dịch: name 'order_type' is not defined
2025-03-20 16:24:05,999 - root - ERROR - Lỗi khi tải dữ liệu giao dịch: name 'order_type' is not defined
2025-03-20 16:31:05,728 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:40:19,884 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:40:20,345 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:40:30,383 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:40:37,440 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:40:37,743 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:40:58,384 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:40:58,696 - controllers.trade_controller - ERROR - Error getting positions: 'leverage'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 217, in get_binance_trades
    leverage = int(position['leverage'])
                   ~~~~~~~~^^^^^^^^^^^^
KeyError: 'leverage'
2025-03-20 16:42:36,144 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:59:18,652 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 16:59:18,853 - controllers.trade_controller - ERROR - Error getting positions: 'BinanceClientModel' object has no attribute 'futures_account'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 198, in get_binance_trades
    account_info = self.binance_client.futures_account()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BinanceClientModel' object has no attribute 'futures_account'
2025-03-20 17:02:11,239 - controllers.main_controller - INFO - Successfully connected to Binance API
2025-03-20 17:02:11,296 - controllers.trade_controller - ERROR - Error getting positions: 'BinanceClientModel' object has no attribute 'futures_account'
Traceback (most recent call last):
  File "d:\Python\Biance_ver2\binance_futures_app\controllers\trade_controller.py", line 198, in get_binance_trades
    account_info = self.binance_client.futures_account()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BinanceClientModel' object has no attribute 'futures_account'
